# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ "ft-simulate-bus-motion-14" ]
  pull_request:
    branches: [ "ft-simulate-bus-motion-14" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 16.x
        os: 
          - ubuntu-latest

    env:
      USER_NAME_FOR_TEST: ${{secrets.USER_NAME_FOR_TEST}}
      PASSWORD_FOR_TEST: ${{secrets.PASSWORD_FOR_TEST}}
      PORT_FOR_TEST: ${{secrets.PORT_FOR_TEST}}
      DB_TEST_NAME: ${{secrets.DB_TEST_NAME}}
      HOST_FOR_TEST: ${{secrets.HOST_FOR_TEST}}
      DIALECT_FOR_ALL_DB: ${{secrets.DIALECT_FOR_ALL_DB}}
      TEST_URI_DATABASE: ${{secrets.TEST_URI_DATABASE}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    - name: Run the test
      run: npm run coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
